# two goods
Qa = Ra*(Aa*Ra*Sa + Ab*Rb*Sb - Ia*Ra - Ib*Rb + sqrt(Aa**2*Ra**2*Sa**2 + 2*Aa*Ab*Ra*Rb*Sa*Sb - 2*Aa*Ia*Ra**2*Sa - 2*Aa*Ib*Ra*Rb*Sa + Ab**2*Rb **
                                                    2*Sb**2 - 2*Ab*Ia*Ra*Rb*Sb - 2*Ab*Ib*Rb**2*Sb + Ia**2*Ra**2 + 2*Ia*Ib*Ra*Rb + Ib**2*Rb**2 + 2*P*Ra**2*Sa + 2*P*Rb**2*Sb))/(Ra**2*Sa + Rb**2*Sb)
Qb = Rb*(Aa*Ra*Sa + Ab*Rb*Sb - Ia*Ra - Ib*Rb + sqrt(Aa**2*Ra**2*Sa**2 + 2*Aa*Ab*Ra*Rb*Sa*Sb - 2*Aa*Ia*Ra**2*Sa - 2*Aa*Ib*Ra*Rb*Sa + Ab**2*Rb **
                                                    2*Sb**2 - 2*Ab*Ia*Ra*Rb*Sb - 2*Ab*Ib*Rb**2*Sb + Ia**2*Ra**2 + 2*Ia*Ib*Ra*Rb + Ib**2*Rb**2 + 2*P*Ra**2*Sa + 2*P*Rb**2*Sb))/(Ra**2*Sa + Rb**2*Sb)

# three goods
Qa = Ra*(Aa*Ra*Sa + Ab*Rb*Sb + Ac*Rc*Sc - Ia*Ra - Ib*Rb - Ic*Rc + sqrt(Aa**2*Ra**2*Sa**2 + 2*Aa*Ab*Ra*Rb*Sa*Sb + 2*Aa*Ac*Ra*Rc*Sa*Sc - 2*Aa*Ia*Ra**2*Sa - 2*Aa*Ib*Ra*Rb*Sa - 2*Aa*Ic*Ra*Rc*Sa + Ab**2*Rb**2*Sb**2 + 2*Ab*Ac*Rb*Rc*Sb*Sc - 2*Ab*Ia*Ra*Rb*Sb - 2*Ab*Ib*Rb**2 *
                                                                       Sb - 2*Ab*Ic*Rb*Rc*Sb + Ac**2*Rc**2*Sc**2 - 2*Ac*Ia*Ra*Rc*Sc - 2*Ac*Ib*Rb*Rc*Sc - 2*Ac*Ic*Rc**2*Sc + Ia**2*Ra**2 + 2*Ia*Ib*Ra*Rb + 2*Ia*Ic*Ra*Rc + Ib**2*Rb**2 + 2*Ib*Ic*Rb*Rc + Ic**2*Rc**2 + 2*P*Ra**2*Sa + 2*P*Rb**2*Sb + 2*P*Rc**2*Sc))/(Ra**2*Sa + Rb**2*Sb + Rc**2*Sc)
Qb = Rb*(Aa*Ra*Sa + Ab*Rb*Sb + Ac*Rc*Sc - Ia*Ra - Ib*Rb - Ic*Rc + sqrt(Aa**2*Ra**2*Sa**2 + 2*Aa*Ab*Ra*Rb*Sa*Sb + 2*Aa*Ac*Ra*Rc*Sa*Sc - 2*Aa*Ia*Ra**2*Sa - 2*Aa*Ib*Ra*Rb*Sa - 2*Aa*Ic*Ra*Rc*Sa + Ab**2*Rb**2*Sb**2 + 2*Ab*Ac*Rb*Rc*Sb*Sc - 2*Ab*Ia*Ra*Rb*Sb - 2*Ab*Ib*Rb**2 *
                                                                       Sb - 2*Ab*Ic*Rb*Rc*Sb + Ac**2*Rc**2*Sc**2 - 2*Ac*Ia*Ra*Rc*Sc - 2*Ac*Ib*Rb*Rc*Sc - 2*Ac*Ic*Rc**2*Sc + Ia**2*Ra**2 + 2*Ia*Ib*Ra*Rb + 2*Ia*Ic*Ra*Rc + Ib**2*Rb**2 + 2*Ib*Ic*Rb*Rc + Ic**2*Rc**2 + 2*P*Ra**2*Sa + 2*P*Rb**2*Sb + 2*P*Rc**2*Sc))/(Ra**2*Sa + Rb**2*Sb + Rc**2*Sc)
Qc = Rc*(Aa*Ra*Sa + Ab*Rb*Sb + Ac*Rc*Sc - Ia*Ra - Ib*Rb - Ic*Rc + sqrt(Aa**2*Ra**2*Sa**2 + 2*Aa*Ab*Ra*Rb*Sa*Sb + 2*Aa*Ac*Ra*Rc*Sa*Sc - 2*Aa*Ia*Ra**2*Sa - 2*Aa*Ib*Ra*Rb*Sa - 2*Aa*Ic*Ra*Rc*Sa + Ab**2*Rb**2*Sb**2 + 2*Ab*Ac*Rb*Rc*Sb*Sc - 2*Ab*Ia*Ra*Rb*Sb - 2*Ab*Ib*Rb**2 *
                                                                       Sb - 2*Ab*Ic*Rb*Rc*Sb + Ac**2*Rc**2*Sc**2 - 2*Ac*Ia*Ra*Rc*Sc - 2*Ac*Ib*Rb*Rc*Sc - 2*Ac*Ic*Rc**2*Sc + Ia**2*Ra**2 + 2*Ia*Ib*Ra*Rb + 2*Ia*Ic*Ra*Rc + Ib**2*Rb**2 + 2*Ib*Ic*Rb*Rc + Ic**2*Rc**2 + 2*P*Ra**2*Sa + 2*P*Rb**2*Sb + 2*P*Rc**2*Sc))/(Ra**2*Sa + Rb**2*Sb + Rc**2*Sc)

# four goods
Qa = Ra*(Aa*Ra*Sa + Ab*Rb*Sb + Ac*Rc*Sc + Ad*Rd*Sd - Ia*Ra - Ib*Rb - Ic*Rc - Id*Rd + sqrt(Aa**2*Ra**2*Sa**2 + 2*Aa*Ab*Ra*Rb*Sa*Sb + 2*Aa*Ac*Ra*Rc*Sa*Sc + 2*Aa*Ad*Ra*Rd*Sa*Sd - 2*Aa*Ia*Ra**2*Sa - 2*Aa*Ib*Ra*Rb*Sa - 2*Aa*Ic*Ra*Rc*Sa - 2*Aa*Id*Ra*Rd*Sa + Ab**2*Rb**2*Sb**2 + 2*Ab*Ac*Rb*Rc*Sb*Sc + 2*Ab*Ad*Rb*Rd*Sb*Sd - 2*Ab*Ia*Ra*Rb*Sb - 2*Ab*Ib*Rb**2*Sb - 2*Ab*Ic*Rb*Rc*Sb - 2*Ab*Id*Rb*Rd*Sb + Ac**2*Rc**2*Sc**2 + 2*Ac*Ad*Rc*Rd*Sc *
                                                                                          Sd - 2*Ac*Ia*Ra*Rc*Sc - 2*Ac*Ib*Rb*Rc*Sc - 2*Ac*Ic*Rc**2*Sc - 2*Ac*Id*Rc*Rd*Sc + Ad**2*Rd**2*Sd**2 - 2*Ad*Ia*Ra*Rd*Sd - 2*Ad*Ib*Rb*Rd*Sd - 2*Ad*Ic*Rc*Rd*Sd - 2*Ad*Id*Rd**2*Sd + Ia**2*Ra**2 + 2*Ia*Ib*Ra*Rb + 2*Ia*Ic*Ra*Rc + 2*Ia*Id*Ra*Rd + Ib**2*Rb**2 + 2*Ib*Ic*Rb*Rc + 2*Ib*Id*Rb*Rd + Ic**2*Rc**2 + 2*Ic*Id*Rc*Rd + Id**2*Rd**2 + 2*P*Ra**2*Sa + 2*P*Rb**2*Sb + 2*P*Rc**2*Sc + 2*P*Rd**2*Sd))/(Ra**2*Sa + Rb**2*Sb + Rc**2*Sc + Rd**2*Sd)
Qb = Rb*(Aa*Ra*Sa + Ab*Rb*Sb + Ac*Rc*Sc + Ad*Rd*Sd - Ia*Ra - Ib*Rb - Ic*Rc - Id*Rd + sqrt(Aa**2*Ra**2*Sa**2 + 2*Aa*Ab*Ra*Rb*Sa*Sb + 2*Aa*Ac*Ra*Rc*Sa*Sc + 2*Aa*Ad*Ra*Rd*Sa*Sd - 2*Aa*Ia*Ra**2*Sa - 2*Aa*Ib*Ra*Rb*Sa - 2*Aa*Ic*Ra*Rc*Sa - 2*Aa*Id*Ra*Rd*Sa + Ab**2*Rb**2*Sb**2 + 2*Ab*Ac*Rb*Rc*Sb*Sc + 2*Ab*Ad*Rb*Rd*Sb*Sd - 2*Ab*Ia*Ra*Rb*Sb - 2*Ab*Ib*Rb**2*Sb - 2*Ab*Ic*Rb*Rc*Sb - 2*Ab*Id*Rb*Rd*Sb + Ac**2*Rc**2*Sc**2 + 2*Ac*Ad*Rc*Rd*Sc *
                                                                                          Sd - 2*Ac*Ia*Ra*Rc*Sc - 2*Ac*Ib*Rb*Rc*Sc - 2*Ac*Ic*Rc**2*Sc - 2*Ac*Id*Rc*Rd*Sc + Ad**2*Rd**2*Sd**2 - 2*Ad*Ia*Ra*Rd*Sd - 2*Ad*Ib*Rb*Rd*Sd - 2*Ad*Ic*Rc*Rd*Sd - 2*Ad*Id*Rd**2*Sd + Ia**2*Ra**2 + 2*Ia*Ib*Ra*Rb + 2*Ia*Ic*Ra*Rc + 2*Ia*Id*Ra*Rd + Ib**2*Rb**2 + 2*Ib*Ic*Rb*Rc + 2*Ib*Id*Rb*Rd + Ic**2*Rc**2 + 2*Ic*Id*Rc*Rd + Id**2*Rd**2 + 2*P*Ra**2*Sa + 2*P*Rb**2*Sb + 2*P*Rc**2*Sc + 2*P*Rd**2*Sd))/(Ra**2*Sa + Rb**2*Sb + Rc**2*Sc + Rd**2*Sd)
Qc = Rc*(Aa*Ra*Sa + Ab*Rb*Sb + Ac*Rc*Sc + Ad*Rd*Sd - Ia*Ra - Ib*Rb - Ic*Rc - Id*Rd + sqrt(Aa**2*Ra**2*Sa**2 + 2*Aa*Ab*Ra*Rb*Sa*Sb + 2*Aa*Ac*Ra*Rc*Sa*Sc + 2*Aa*Ad*Ra*Rd*Sa*Sd - 2*Aa*Ia*Ra**2*Sa - 2*Aa*Ib*Ra*Rb*Sa - 2*Aa*Ic*Ra*Rc*Sa - 2*Aa*Id*Ra*Rd*Sa + Ab**2*Rb**2*Sb**2 + 2*Ab*Ac*Rb*Rc*Sb*Sc + 2*Ab*Ad*Rb*Rd*Sb*Sd - 2*Ab*Ia*Ra*Rb*Sb - 2*Ab*Ib*Rb**2*Sb - 2*Ab*Ic*Rb*Rc*Sb - 2*Ab*Id*Rb*Rd*Sb + Ac**2*Rc**2*Sc**2 + 2*Ac*Ad*Rc*Rd*Sc *
                                                                                          Sd - 2*Ac*Ia*Ra*Rc*Sc - 2*Ac*Ib*Rb*Rc*Sc - 2*Ac*Ic*Rc**2*Sc - 2*Ac*Id*Rc*Rd*Sc + Ad**2*Rd**2*Sd**2 - 2*Ad*Ia*Ra*Rd*Sd - 2*Ad*Ib*Rb*Rd*Sd - 2*Ad*Ic*Rc*Rd*Sd - 2*Ad*Id*Rd**2*Sd + Ia**2*Ra**2 + 2*Ia*Ib*Ra*Rb + 2*Ia*Ic*Ra*Rc + 2*Ia*Id*Ra*Rd + Ib**2*Rb**2 + 2*Ib*Ic*Rb*Rc + 2*Ib*Id*Rb*Rd + Ic**2*Rc**2 + 2*Ic*Id*Rc*Rd + Id**2*Rd**2 + 2*P*Ra**2*Sa + 2*P*Rb**2*Sb + 2*P*Rc**2*Sc + 2*P*Rd**2*Sd))/(Ra**2*Sa + Rb**2*Sb + Rc**2*Sc + Rd**2*Sd)
Qd = Rd*(Aa*Ra*Sa + Ab*Rb*Sb + Ac*Rc*Sc + Ad*Rd*Sd - Ia*Ra - Ib*Rb - Ic*Rc - Id*Rd + sqrt(Aa**2*Ra**2*Sa**2 + 2*Aa*Ab*Ra*Rb*Sa*Sb + 2*Aa*Ac*Ra*Rc*Sa*Sc + 2*Aa*Ad*Ra*Rd*Sa*Sd - 2*Aa*Ia*Ra**2*Sa - 2*Aa*Ib*Ra*Rb*Sa - 2*Aa*Ic*Ra*Rc*Sa - 2*Aa*Id*Ra*Rd*Sa + Ab**2*Rb**2*Sb**2 + 2*Ab*Ac*Rb*Rc*Sb*Sc + 2*Ab*Ad*Rb*Rd*Sb*Sd - 2*Ab*Ia*Ra*Rb*Sb - 2*Ab*Ib*Rb**2*Sb - 2*Ab*Ic*Rb*Rc*Sb - 2*Ab*Id*Rb*Rd*Sb + Ac**2*Rc**2*Sc**2 + 2*Ac*Ad*Rc*Rd*Sc *
                                                                                          Sd - 2*Ac*Ia*Ra*Rc*Sc - 2*Ac*Ib*Rb*Rc*Sc - 2*Ac*Ic*Rc**2*Sc - 2*Ac*Id*Rc*Rd*Sc + Ad**2*Rd**2*Sd**2 - 2*Ad*Ia*Ra*Rd*Sd - 2*Ad*Ib*Rb*Rd*Sd - 2*Ad*Ic*Rc*Rd*Sd - 2*Ad*Id*Rd**2*Sd + Ia**2*Ra**2 + 2*Ia*Ib*Ra*Rb + 2*Ia*Ic*Ra*Rc + 2*Ia*Id*Ra*Rd + Ib**2*Rb**2 + 2*Ib*Ic*Rb*Rc + 2*Ib*Id*Rb*Rd + Ic**2*Rc**2 + 2*Ic*Id*Rc*Rd + Id**2*Rd**2 + 2*P*Ra**2*Sa + 2*P*Rb**2*Sb + 2*P*Rc**2*Sc + 2*P*Rd**2*Sd))/(Ra**2*Sa + Rb**2*Sb + Rc**2*Sc + Rd**2*Sd)
